main: net.ddns.maikeio.elytra_auto_equipper.ElytraAutoEquipper
name: ElytraAutoEquipper
version: 1.0
description: Plugin for switching chestplate and elytra automatically
api-version: 1.16
author: Maikeio
website: www.maikeio.ddns.net